Ajout de doc librairies (images,couleurs,constantes)
witsa/synapps pull request #443
Opened 2022-03-22 16:18 UTC by Raphwit

2022-03-22 17:11 UTC, manufitoussiwit requested changes

2022-03-22 17:11 UTC, manufitoussiwit commented on concepts/actor-types/input-text-area.md
> +{% endfor %}
Le contenu des collections va prendre la place du `for`

2022-03-22 17:11 UTC, manufitoussiwit commented on concepts/actor-types/input-text-box.md
> +{% assign sorted = site.input_text_box_properties | sort: 'order' %}
Le contenu des collections va prendre la place du `for`

2022-03-22 17:11 UTC, manufitoussiwit commented on collections/_input_text_area_properties/text_area.md
> +>*Note*
J'ai commencé à normaliser ces petits encarts: 
ici, ce serait plutôt : 
```markdown
> 📌 **REMARQUE**<br>
> Il n'est pas possible de décorer le texte au sein de cet acteur, pour ajouter de la décoration au texte il est préférable d'utiliser un acteur HTML.
```

Y a aussi : 
```markdown
> 💡 **ASTUCE**<br>
> Une astuce...
```
```markdown
>⚠️ **ATTENTION**<br>
> Un truc important...
```

```markdown
> ✔️ **CONSEIL**<br>
> Un conseil...
```

2022-03-23 08:49 UTC, Raphwit commented
@manufitoussiwit J'ai commit les changements vis à vis de tes commentaires

2022-03-23 09:23 UTC, manufitoussiwit approved these changes

2022-03-23 09:25 UTC, merged